name: Playwright

on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main

jobs:
  playwright-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.35.0-jammy
    steps:
      # Checkout and setup
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: npm install
      # Run Playwright tests
      - name: Run Playwright tests
        run: npm run test
      # Upload the test result artifacts
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
